### ISSUE TITLE
What is the point?

### ISSUE THREAD

**Issue by Joshua-Ashton** [portabletext/portabletext#6]
JSON really isn't suited for markup of documents (at least by humans.)
The whole format of what you've shown is incredibly ugly, unreadable and looks like a nightmare to debug. The "_" notation is also yucky.

There are plenty of great formats (such as XML, HTML, Jade, Pug,) etc for marking up documents, and they all have these key features:

- Human readable
- Easy to parse
- Easy to understand at a glance

With the examples you've provided, portabletext has none of these features and its *incredibly* difficult to visualize what is actually going on here.

JSON is also significantly harder to parse (having things such as arrays, commas, etc,) than other formats such as XML.

I also believe this sort of thing isn't something we need a standard or abstraction for either way. Is there any real advantage to using XML/HTML and just converting directly from those to other formats? Those are languages that people actually use -- and there would be very little advantage to having an IR-styled system in this case?

**Comment by kmelve** [comment]
Thank you for your comments!

The `_` notation is to express “native keys”, since users can make their own artbitrary keys. It's a fairly widespread convention. 

We try to make it clear in the preface that this isn’t a markup language as such, but a specification for how UI-editors can store rich text data with additional custom content types that can be serialized into pretty much any markup language. 

We’re aware of XML but chose to go with JSON because of its ubiquitousness on the web, and constraints. XML soon becomes a mess in the hands of real users in the real world. [This blog](https://twobithistory.org/2017/09/21/the-rise-and-rise-of-json.html) sheds some light on that. You can also get some insight into our thinking in [this blog post](https://www.sanity.io/blog/why-structured-text-is-awesome-and-you-totally-want-it-in-your-cms). 

Also, we have used this format with [sanity.io](https://www.sanity.io) for a couple of years, so we know it’s useful. We'll add more examples, use cases and tools going forward. 

I'll close this issue since it's not contributing to the specification – but I appriciate the opportunity to clear some things up.

**Comment by Joshua-Ashton** [comment]
No problem, thanks for your reply and clearing up a few things. Sorry if I came across as a bit snarky.
